locality = Locations::Locality.find_by(name: "Lamut")
locality.barangays.find_or_create_by!(name: "Ambasa")
locality.barangays.find_or_create_by!(name: "Bimpal")
locality.barangays.find_or_create_by!(name: "Hapid")
locality.barangays.find_or_create_by!(name: "Holowon")
locality.barangays.find_or_create_by!(name: "Lawig")
locality.barangays.find_or_create_by!(name: "Lucban")
locality.barangays.find_or_create_by!(name: "Mabatobato")
locality.barangays.find_or_create_by!(name: "Magulon")
locality.barangays.find_or_create_by!(name: "Nayon")
locality.barangays.find_or_create_by!(name: "Panopdopan")
locality.barangays.find_or_create_by!(name: "Payawan")
locality.barangays.find_or_create_by!(name: "Pieza")
locality.barangays.find_or_create_by!(name: "Poblacion East")
locality.barangays.find_or_create_by!(name: "Poblacion West")
locality.barangays.find_or_create_by!(name: "Pugol")
locality.barangays.find_or_create_by!(name: "Salamague")
locality.barangays.find_or_create_by!(name: "Sanafe")
locality.barangays.find_or_create_by!(name: "Umilag")
