# province = Locations::Province.find_or_create_by(name: "Benguet")
# mayors_permit_fee_calculation_config = Configurations::MayorsPermitFeeCalculationConfig.create(config_type: "based_on_business_tax")
# capital_tax_revenue_account = Accounting::Revenue.find_by(name: 'Capital Tax')
#
# locality = Locations::Locality.city.find_or_create_by(
#   name: "Baguio",
#   province: province,
#   capital_tax_revenue_account: capital_tax_revenue_account,
#   mayors_permit_fee_calculation_config: mayors_permit_fee_calculation_config)
#
# locality.barangays.find_or_create_by(name: "Abanao-Zandueta-Kayong-Chugum")
# locality.barangays.find_or_create_by(name: "Alfonso Tabora")
# locality.barangays.find_or_create_by(name: "Ambiong")
# locality.barangays.find_or_create_by(name: "Andres Bonifacio")
# locality.barangays.find_or_create_by(name: "Apugan-Loakan")
# locality.barangays.find_or_create_by(name: "Asin Road")
# locality.barangays.find_or_create_by(name: "Atok Trail")
# locality.barangays.find_or_create_by(name: "Aurora Hill Proper")
# locality.barangays.find_or_create_by(name: "Aurora Hill, North Central")
# locality.barangays.find_or_create_by(name: "Aurora Hill, South Central")
# locality.barangays.find_or_create_by(name: "Bagong Lipunan (Market Area)")
# locality.barangays.find_or_create_by(name: "Bakakeng Central")
# locality.barangays.find_or_create_by(name: "Bakakeng North")
# locality.barangays.find_or_create_by(name: "Bal-Marcoville (Marcoville)")
# locality.barangays.find_or_create_by(name: "Balsigan")
# locality.barangays.find_or_create_by(name: "Bayan Park East")
# locality.barangays.find_or_create_by(name: "Bayan Park Village")
# locality.barangays.find_or_create_by(name: "Bayan Park West (Bayan Park)")
# locality.barangays.find_or_create_by(name: "BGH Compound")
# locality.barangays.find_or_create_by(name: "Bonifacio-Caguioa-Rimando")
# locality.barangays.find_or_create_by(name: "Brookside")
# locality.barangays.find_or_create_by(name: "Brookspoint")
# locality.barangays.find_or_create_by(name: "Cabinet Hill-Teacher’s Camp")
# locality.barangays.find_or_create_by(name: "Camdas Subdivision")
# locality.barangays.find_or_create_by(name: "Camp 7")
# locality.barangays.find_or_create_by(name: "Camp 8")
# locality.barangays.find_or_create_by(name: "Camp Allen")
# locality.barangays.find_or_create_by(name: "Campo Filipino")
# locality.barangays.find_or_create_by(name: "City Camp Central")
# locality.barangays.find_or_create_by(name: "City Camp Proper")
# locality.barangays.find_or_create_by(name: "Country Club Village")
# locality.barangays.find_or_create_by(name: "Cresencia Village Barangay")
# locality.barangays.find_or_create_by(name: "Dagsian, Lower")
# locality.barangays.find_or_create_by(name: "Dagsian, Upper")
# locality.barangays.find_or_create_by(name: "Department of Public Services(DPS) Compound")
# locality.barangays.find_or_create_by(name: "Dizon Subdivision")
# locality.barangays.find_or_create_by(name: "Dominican Hill Mirador")
# locality.barangays.find_or_create_by(name: "Dontogan")
# locality.barangays.find_or_create_by(name: "Engineers’ Hill")
# locality.barangays.find_or_create_by(name: "Fairview Village")
# locality.barangays.find_or_create_by(name: "Ferdinand (Happy Homes-Campo)")
# locality.barangays.find_or_create_by(name: "Fort del Pilar")
# locality.barangays.find_or_create_by(name: "Gabriela Silang")
# locality.barangays.find_or_create_by(name: "General Emilio F. Aguinaldo")
# locality.barangays.find_or_create_by(name: "General Luna, Lower")
# locality.barangays.find_or_create_by(name: "General Luna, Upper")
# locality.barangays.find_or_create_by(name: "Gibraltar")
# locality.barangays.find_or_create_by(name: "Greenwater Village")
# locality.barangays.find_or_create_by(name: "Guisad Central")
# locality.barangays.find_or_create_by(name: "Guisad Sorong")
# locality.barangays.find_or_create_by(name: "Happy Hollow")
# locality.barangays.find_or_create_by(name: "Happy Homes (Happy Homes-Lucban)")
# locality.barangays.find_or_create_by(name: "Harrison-Claudio Carantes")
# locality.barangays.find_or_create_by(name: "Hillside")
# locality.barangays.find_or_create_by(name: "Holy Ghost Extension")
# locality.barangays.find_or_create_by(name: "Holy Ghost Proper")
# locality.barangays.find_or_create_by(name: "Honeymoon (Honeymoon-Holy Ghost)")
# locality.barangays.find_or_create_by(name: "Imelda R. Marcos (La Salle)")
# locality.barangays.find_or_create_by(name: "Imelda Village")
# locality.barangays.find_or_create_by(name: "Irisan")
# locality.barangays.find_or_create_by(name: "Kabayanihan")
# locality.barangays.find_or_create_by(name: "Kagitingan")
# locality.barangays.find_or_create_by(name: "Kayang Extension")
# locality.barangays.find_or_create_by(name: "Kayang-Hilltop")
# locality.barangays.find_or_create_by(name: "Kias")
# locality.barangays.find_or_create_by(name: "Legarda-Burnham-Kisad")
# locality.barangays.find_or_create_by(name: "Liwanag-Loakan")
# locality.barangays.find_or_create_by(name: "Loakan Proper")
# locality.barangays.find_or_create_by(name: "Lopez Jaena")
# locality.barangays.find_or_create_by(name: "Lourdes Subdivision Extension")
# locality.barangays.find_or_create_by(name: "Lourdes Subdivision, Lower")
# locality.barangays.find_or_create_by(name: "Lourdes Subdivision, Proper")
# locality.barangays.find_or_create_by(name: "Lualhati")
# locality.barangays.find_or_create_by(name: "Lucnab")
# locality.barangays.find_or_create_by(name: "Magsaysay Private Road")
# locality.barangays.find_or_create_by(name: "Magsaysay, Lower")
# locality.barangays.find_or_create_by(name: "Magsaysay, Upper")
# locality.barangays.find_or_create_by(name: "Malcolm Square-Perfecto")
# locality.barangays.find_or_create_by(name: "Manuel A. Roxas")
# locality.barangays.find_or_create_by(name: "Market Subdivision, Upper")
# locality.barangays.find_or_create_by(name: "Middle Quezon Hill Subdivision")
# locality.barangays.find_or_create_by(name: "Military Cut-off")
# locality.barangays.find_or_create_by(name: "Mines View Park")
# locality.barangays.find_or_create_by(name: "Modern Site, East")
# locality.barangays.find_or_create_by(name: "Modern Site, West")
# locality.barangays.find_or_create_by(name: "MRR-Queen Of Peace")
# locality.barangays.find_or_create_by(name: "New Lucban")
# locality.barangays.find_or_create_by(name: "Outlook Drive")
# locality.barangays.find_or_create_by(name: "Pacdal")
# locality.barangays.find_or_create_by(name: "Padre Burgos")
# locality.barangays.find_or_create_by(name: "Padre Zamora")
# locality.barangays.find_or_create_by(name: "Palma-Urbano (Cari?o-Palma)")
# locality.barangays.find_or_create_by(name: "Phil-Am")
# locality.barangays.find_or_create_by(name: "Pinget")
# locality.barangays.find_or_create_by(name: "Pinsao Pilot Project")
# locality.barangays.find_or_create_by(name: "Pinsao Proper")
# locality.barangays.find_or_create_by(name: "Pucsusan")
# locality.barangays.find_or_create_by(name: "Puliwes")
# locality.barangays.find_or_create_by(name: "Quezon Hill Proper")
# locality.barangays.find_or_create_by(name: "Quezon Hill, Upper")
# locality.barangays.find_or_create_by(name: "Quirino Hill, East")
# locality.barangays.find_or_create_by(name: "Quirino Hill, Lower")
# locality.barangays.find_or_create_by(name: "Quirino Hill, Middle")
# locality.barangays.find_or_create_by(name: "Quirino Hill, West")
# locality.barangays.find_or_create_by(name: "Quirino-Magsaysay, Upper")
# locality.barangays.find_or_create_by(name: "Rizal Monument Area")
# locality.barangays.find_or_create_by(name: "Rock Quarry, Lower")
# locality.barangays.find_or_create_by(name: "Rock Quarry, Middle")
# locality.barangays.find_or_create_by(name: "Rock Quarry, Upper")
# locality.barangays.find_or_create_by(name: "Saint Joseph Village")
# locality.barangays.find_or_create_by(name: "Salud Mitra")
# locality.barangays.find_or_create_by(name: "San Antonio Village")
# locality.barangays.find_or_create_by(name: "San Luis Village")
# locality.barangays.find_or_create_by(name: "San Roque Village")
# locality.barangays.find_or_create_by(name: "San Vicente")
# locality.barangays.find_or_create_by(name: "Sanitary Camp South")
# locality.barangays.find_or_create_by(name: "Sanitary Camp, North")
# locality.barangays.find_or_create_by(name: "Santa Escolastica")
# locality.barangays.find_or_create_by(name: "Santo Rosario Valley")
# locality.barangays.find_or_create_by(name: "Santo Tomas Proper")
# locality.barangays.find_or_create_by(name: "Santo Tomas School Area")
# locality.barangays.find_or_create_by(name: "Scout Barrio")
# locality.barangays.find_or_create_by(name: "Session Road Area")
# locality.barangays.find_or_create_by(name: "Slaughter House Area")
# locality.barangays.find_or_create_by(name: "SLU-SVP Housing Village")
# locality.barangays.find_or_create_by(name: "South Drive")
# locality.barangays.find_or_create_by(name: "Teodora Alonzo")
# locality.barangays.find_or_create_by(name: "Trancoville")
# locality.barangays.find_or_create_by(name: "Victoria Village")
